# Generated by Django 6.1.1 on 2026-09-18 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('brand', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('sku', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('reviews', models.JSONField(blank=True, null=True)),
                ('detail_loaded_at', models.DateTimeField(blank=True, null=True)),
                ('structure_changed_at', models.DateTimeField(blank=True, null=True)),
                ('structure_note', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=24)),
                ('run_at', models.DateTimeField(db_index=True)),
                ('payload', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=320, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('slot_at', models.DateTimeField(db_index=True)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('price', models.FloatField(blank=True, null=True)),
                ('was_price', models.FloatField(blank=True, null=True)),
                ('discount_pct', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('stock_label', models.CharField(blank=True, max_length=120, null=True)),
                ('stock_count', models.IntegerField(blank=True, null=True)),
                ('layout_revision', models.IntegerField(blank=True, null=True)),
                ('structure_changed', models.BooleanField(default=False)),
                ('trigger', models.CharField(default='track', max_length=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='app.product')),
            ],
            options={
                'db_table': 'price_snapshots',
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tracker_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('attempt', models.IntegerField(default=1)),
                ('outcome', models.CharField(db_index=True, max_length=16)),
                ('error_kind', models.CharField(blank=True, max_length=16, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('price', models.FloatField(blank=True, null=True)),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='app.product')),
            ],
            options={
                'db_table': 'scrape_logs',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('refresh_minutes', models.IntegerField(default=120)),
                ('active', models.BooleanField(default=True)),
                ('alert_on_price_drop', models.BooleanField(default=True)),
                ('price_drop_threshold_pct', models.FloatField(blank=True, null=True)),
                ('alert_on_back_in_stock', models.BooleanField(default=True)),
                ('last_covered_slot', models.DateTimeField(blank=True, null=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='app.user')),
            ],
            options={
                'db_table': 'trackers',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('tracker_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('type', models.CharField(db_index=True, max_length=24)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('threshold_pct', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.user')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='TrackerHistory',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_links', to='app.product')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_links', to='app.pricesnapshot')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_links', to='app.tracker')),
            ],
            options={
                'db_table': 'tracker_history',
                'constraints': [models.UniqueConstraint(fields=('tracker', 'snapshot'), name='uq_history_tracker_snapshot')],
            },
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='uq_tracker_user_product'),
        ),
    ]
